[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
db.workspace = true
chrono.workspace = true
anyhow.workspace = true
diesel.workspace = true
log = "0.4.27"

[lints.clippy]
too_many_arguments = { level = "allow" }
