[package]
name = "rex-db"
version = "0.3.0"
edition = "2024"
description = "Rex database models using diesel"
homepage = "https://github.com/TheRustyPickle/Rex"
repository = "https://github.com/TheRustyPickle/Rex"
license = "MIT"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
diesel.workspace = true
diesel_migrations = "2.3.2"
libsqlite3-sys = { version = "0.38.2", features = ["bundled"] }
rex-shared.workspace = true
strum.workspace = true
strum_macros.workspace = true
