[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
shared.workspace = true
libsqlite3-sys = { version = "0.35.0", features = ["bundled"] }
diesel.workspace = true
chrono.workspace = true
diesel_migrations = "2.2.0"
anyhow.workspace = true
